version: 0.2

phases:
  install:
    commands:
      - "npm add --global nx@latest"
      - "yarn install"

  build:
    commands:
      - "npx nx build client"
      - "npx nx export client"

artifacts:
  baseDirectory: dist/apps/client/.next
  files:
    - "dist/apps/client/**/*"
  discard-paths: yes
