version: 0.2

phases:
  install:
    commands:
      - "npm add --global nx@latest"
      - "yarn install"

  build:
    commands:
      - "nx build client"
      - "nx export client"

artifacts:
  files:
    - "**/*"
  base-directory: "dist/exported"
