version: 0.2

phases:
  install:
    commands:
      - "npm add --global nx@latest"
      - "yarn install"

  build:
    commands:
      - "npx nx build client"
      - "npx nx export client"
      - "echo TESTING....."
      - "echo $(ls)"
      - "echo $(ls dist)"

artifacts:
  files:
    - "**/*"
  base-directory: "dist/apps/client/exported"
