version: 0.2

phases:
  install:
    commands:
      - "echo testing"

  build:
    commands:
      - "echo $(ls)"

  post_build:
    commands:
      - "echo $CLOUDFRONT_ID"

artifacts:
  files:
    - index.html
