version: 0.2

phases:
  install:
    commands:
      - "npm add --global nx@latest"
      - "yarn install"

  build:
    commands:
      - "npx nx build client"
      - "npx nx export client"

artifacts:
  files:
    - "dist/apps/client/exported/*"
  discard-paths: yes

cache:
  paths:
    - "node_modules"
